\documentclass[final]{beamer}
\usepackage{graphicx}
\usepackage{color}
\usepackage{amsmath}
\usepackage{epstopdf}
\usepackage{multicol}
\usepackage{ragged2e}

%\usepackage{polski}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{grffile}
\mode<presentation>{\usetheme{CambridgeUSPOL}}

\usepackage[utf8]{inputenc}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{natbib}
\usepackage{graphicx}
\usepackage{array,booktabs,tabularx}
\usepackage{epstopdf}
\usepackage[dvipsnames]{xcolor}
\usepackage{colortbl}
\newcolumntype{Z}{>{\centering\arraybackslash}X}

% rysunki
\usepackage{tikz}
\usepackage{ifthen}
\usepackage{xxcolor}
\usetikzlibrary{arrows}
\usetikzlibrary[topaths]
\usetikzlibrary{decorations.pathreplacing}
\usefonttheme[onlymath]{serif}
\boldmath
\usepackage[orientation=portrait,size=a0,scale=1,debug]{beamerposter}                       % e.g. for DIN-A0 poster
%\usepackage[orientation=portrait,size=a1,scale=1.4,grid,debug]{beamerposter}                  % e.g. for DIN-A1 poster, with optional grid and debug output
%\usepackage[size=custom,width=200,height=120,scale=2,debug]{beamerposter}                     % e.g. for custom size poster
%\usepackage[orientation=portrait,size=a0,scale=1.0,printer=rwth-glossy-uv.df]{beamerposter}   % e.g. for DIN-A0 poster with rwth-glossy-uv printer check
% ...
%

\setbeamertemplate{caption}[numbered]

%!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

\newlength{\columnheight}
\setlength{\columnheight}{89cm} % ------------------------------- od jakiej wysokości mają zaczynać się klocki, ale też miejsce dla tytułu autorów, afiliacji
\renewcommand{\thetable}{}
\def\andname{,}
\authornote{}



\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


% Początek posteru
%-------------------------------------------------------------------------------------------------------------------
%--------------------------------------------------------------Tytuł
\title{\huge HaDeX: an R package and web-server for analysis of data from hydrogen deuterium exchange - mass spectrometry experiments} 

% -----------------------------------------------------------Autorzy, mail, afiliacje
\date{}
\author{Weronika Pucha\l{}a\,$^{\text{\sfb 1}}$,
Micha\l{} Burdukiewicz\,$^{\text{\sfb 2}}$,
Micha\l{} Kistowski\,$^{\text{\sfb 1}}$,
Katarzyna D\k{a}browa-D\k{a}browska\,$^{\text{\sfb 1}}$,
Aleksandra E. Badaczewska-Dawid\,$^{\text{\sfb 3}}$,\\ 
Dominik Cysewski\,$^{\text{\sfb 1},*}$,
Micha\l{} Dadlez\,$^{\text{\sfb 1}}$\\
\normaltext{*dominikcysewski@gmail.com}}
\institute{$^{\text{\sf 1}}$Institute of Biochemistry and Biophysics Polish Academy of Sciences, Poland,
$^{\text{\sf 2}}$Faculty of Mathematics and Information Science, Warsaw University of 
Technology, Poland,
$^{\text{\sf 3}}$Faculty of Chemistry, Biological and Chemical Research Center, University of Warsaw, Poland.
}
}

 \begin{frame}
 
\begin{columns}
\begin{column}{.5\textwidth} %------------------------------------------------ szerokość kolumny lewej
\begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
\begin{minipage}[T]{.99\textwidth}
\parbox[t][\columnheight]{\textwidth}
{

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Introduction}
<<echo=FALSE, warning=FALSE, error=FALSE, message=FALSE>>=
library(HaDeX)
library(ggplot2)
library(patchwork)

knitr::opts_chunk$set(out.width=1000, out.height=750)

poster_theme <- theme_bw(base_size = 10) +
                theme(legend.position = "bottom",
                      legend.title = element_blank())

dat <- read_hdx(system.file(package = "HaDeX", "HaDeX/data/KD_190304_Nucb2_EDTA_CaCl2_test02_clusterdata.csv"))

calc_dat <- prepare_dataset(dat,
                             in_state_first = "gg_Nucb2_EDTA_0.001",
                             chosen_state_first = "gg_Nucb2_EDTA_25",
                             out_state_first = "gg_Nucb2_EDTA_1440",
                             in_state_second = "gg_Nucb2_CaCl2_0.001",
                             chosen_state_second = "gg_Nucb2_CaCl2_25",
                             out_state_second = "gg_Nucb2_CaCl2_1440") 

@

\justify Hydrogen-deuterium mass spectrometry (HDX-MS) is a staple tool for monitoring dynamics and interactions of proteins. Due to the sheer size of the HDX-MS results, the data analysis require a dedicated software suite. However, the majority of existing tools provides only point-and-click interfaces to black-box models or does not offer a complete workflow. We propose HaDeX, a novel tool for processing, analysis and visualisation of HDX-MS experiments. HaDeX covers the whole analytic process, including preliminary data exploration, quality control and generation of publication-quality figures. The reproducibility of the whole procedure is ensured with advanced reporting functions. HaDeX is available primarily as a web-server, but his all functionalities are also accessible as the R package (\url{https://CRAN.R-project.org/package=HaDeX}).

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Coverage of the sequence} 

\justify Everything you need to use HaDeX is a DynamiX datafile. In future, the functionality will be available for more than this datafile type. All the calculations are done by our software using default parameters or chosen by user.  
We start our analysis with summary of protein coverage (as shown below). It is provided in two forms, histogram and graphic comparison of positions. Also the reconstruction of the sequence is available - based on experimental data.

\begin{figure}
\includegraphics[width=0.95\columnwidth]{app_coverage.png}
\caption{Screenshot of HaDeX - page with presentation of sequence coverage using example data}
\end{figure}

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Differential plot}

\justify Important aspect of analysing data is comparing results of peptide deuteration in different states. Relative deuteration level used by HaDeX is defined by equation \ref{eq:deut_lev}.

\begin{equation}
D = \frac{D_{t} - D_{0}}{D_{100} - D_{0}}
\label{eq:deut_lev}
\end{equation}

\justify The equation \ref{eq:deut_lev} is a function of three variables (each with its own uncertainty), so there is need to use the Law of Propagation of Uncertainty, defined in equation \ref{eq:law_un}

\begin{equation}
u_{c}(y) = \sqrt{\sum_{k} \left[ \frac{\partial y}{\partial x_{k}} u(x_{k}) \right]^2}
\label{eq:law_un}
\end{equation}

\justify Applying equation \ref{eq:law_un} to equation \ref{eq:deut_lev}, we get deuteration level uncertainty described by equation \ref{eq:deut_lev_un}

\begin{equation}
u_{c}(D) = \sqrt{ \left[ \frac{1}{D_{100}-D_{0}} u(D_{t}) \right]^2 + \left[ \frac{D_{t} - D_{100}}{(D_{100}-D_{0})^2} u(D_{0}) \right]^2 + \left[ \frac{D_{0} - D_{t}}{(D_{100}-D_{0})^2} u(D_{100}) \right]^2}
\label{eq:deut_lev_un}
\end{equation}

\justify Results of deuteration level calculations with their uncertainty are shown on comparison plot, showed below. HaDeX provide both experimental and theroetical calculations, shown side by side for comparison on figure \ref{fig:comp_plots}.
\begin{figure}
<<echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center">>=

 c1 <- comparison_plot(calc_dat = calc_dat,
                 plot_title = "Theoretical fraction exchanged in \nstate comparison in 25 min time",
                 theoretical = TRUE,
                 state_first = "gg_Nucb2_EDTA",
                 state_second = "gg_Nucb2_CaCl2") +
   poster_theme 

 c2 <- comparison_plot(calc_dat = calc_dat,
                 plot_title = "Fraction exchanged in state comparison \nin 25 min time",
                 theoretical = FALSE,
                 state_first = "gg_Nucb2_EDTA",
                 state_second = "gg_Nucb2_CaCl2") +
   poster_theme
 
 c1 + c2
 
 @
\caption{Comparison plots - comparing experimental and theoretical calculations, based on example data.}
\label{fig:comp_plots}
\end{figure}

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Visit us!}

     \url{http://mslab-ibb.pl/shiny/HaDeX/}$\begin{array}{l}
        \begin{figure}[ht]
        \centering
        \scalebox{0.025}{
          \includegraphics{hadex_qr.eps}
        }
        \end{figure}
      \end{array}

\end{block}

}
\end{minipage}
\end{beamercolorbox}
\end{column}


%new column -------------------------------------------------------------------------------------------------    

\begin{column}{.47\textwidth} % ----------------------------------------- szerokość kolumny prawej
\begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
\begin{minipage}[T]{.99\textwidth}  
\parbox[t][\columnheight]{\textwidth}
{

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Woods plot format}

\justify Woods plot format shows diference between results of two different states as described by equation \ref{eq:diff}.

\begin{equation}
diff = D_{1} - D_{2}
\label{eq:diff}
\end{equation}

Equation \ref{eq:diff} is a function of two variables, so applying \ref{eq:law_un} we get uncertainty described by equation \ref{eq:diff_un}.

\begin{equation}
u_{c}(diff) = \sqrt{u(D_{1})^2 + u(D_{2})^2}
\label{eq:diff_un}
\end{equation}

\justify Described calculations lead to results shown on Woods plot format - figure \ref{fig:woods_plots} below.

\begin{figure}
<<echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.align="center">>=

 w1 <- woods_plot(calc_dat = calc_dat,
            plot_title = "Theoretical fraction exchanged between \nstates in 25 min time",
            theoretical = TRUE) +
   poster_theme +
   scale_y_continuous(limits = c(-0.6, 0.8), expand = c(0, 0))
 
 w2 <- woods_plot(calc_dat = calc_dat,
            plot_title = "Fraction exchanged between states \nin 25 min time",
            theoretical = FALSE) +
   poster_theme +
   scale_y_continuous(limits = c(-0.6, 0.8), expand = c(0, 0))
 
 w1 + w2
 
@
\caption{Plots in Woods format - comparing experimental and theoretical calculations, based on example data.}
\label{fig:woods_plots}
\end{figure}

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Quality control}

\justify HaDeX provides additional tools for decision making. A perfect example is quality control function that shows how the mean uncertainty per peptide changes with out time parameter change. The user can see if chosen out time is sufficient for acceptable uncertainty values, or is it better to choose different value.

\begin{figure}
<<echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, fig.align="center", fig.height=7, fig.width=15, out.height=300, out.width=900>>=
 
 result <- quality_control(dat = dat,
                          state_first = "gg_Nucb2_EDTA",
                          state_second = "gg_Nucb2_CaCl2", 
                          chosen_time = 25, 
                          in_time = 0.001)

 ggplot(result[result["time"]>=1,]) + 
  geom_line(aes(x = time, y = avg_err_state_first, color = "avg_err_state_first")) +
  geom_line(aes(x = time, y = avg_err_state_second, color = "avg_err_state_second")) +
  scale_x_log10() +
  labs(x = "log(time) [min]", y = "Average uncertainty", title = "Uncertainty change in out time") + 
  theme_bw(base_size = 25) +
  theme(legend.position = "bottom",
        legend.title = element_blank())

@
\caption{Plot ilustrating uncertainy change depending on used out parameter}
\end{figure}

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Report function}

\justify HaDeX provides report generation - with parameters chosen by user so is fully personalizable. Additionaly, calculated data for plots can be downloaded not only in report form but also in csv/pdf file in panel next to every plot. On figure \ref{fig:rep} are shown available elements of the report - that can be chosen by user and limited strickly for user needs. 

\begin{figure}
\includegraphics[width=0.8\columnwidth]{app_report.png}
\caption{Screenshot of HaDeX - reporting page}
\label{fig:rep}
\end{figure}
\end{block}

\begin{block}{Bibliography}

\vfill

\end{block}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Acknowledgements}

\justify The project is carried out within the TEAM TECH programme of the Foundation for Polish Science co-financed by the European Union under the European Regional Development Fund.(TEAM TECH CORE FACILITY/2016-2/2) „Mass Spectrometry of Biopharmaceuticals-improved methodologies for qualitative, quantitative and structural characterization of drugs, proteinaceous drug targets and diagnostic molecules”

\begin{figure}
\includegraphics[width=0.95\columnwidth]{listwa.png}
\end{figure}

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

}
\end{minipage}
\end{beamercolorbox}
\end{column}
\end{columns}  


\end{frame}


\end{document}